# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'prac_SwiftLint' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for prac_SwiftLint
    
    pod 'SwiftLint'
end
