# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'prac_Map2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for prac_Map2
    pod 'NMapsMap'
 
end
